"""
Data models — the stable contract between the Python engine and the TS extension.

All models serialize to JSON via dataclasses.asdict() for the JSON-RPC layer.
These are the ONLY types that cross the process boundary.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field, asdict
from typing import Any


class CheckStatus(str, enum.Enum):
    """Severity level of a validation check result."""
    PASS = "pass"
    WARN = "warn"
    FAIL = "fail"


class CheckCategory(str, enum.Enum):
    """Logical grouping for check results displayed in the panel."""
    SYNTAX = "syntax"
    STRUCTURE = "structure"
    VARIABLES = "variables"
    COLUMNS = "columns"
    DEPENDENCIES = "dependencies"
    CONNECTIONS = "connections"
    SECURITY = "security"
    BEST_PRACTICES = "best_practices"


class FixImpact(str, enum.Enum):
    """Impact level for AI remediation variants."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


# ---------------------------------------------------------------------------
# Core check result — one per rule evaluation
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CheckResult:
    """
    A single validation finding.

    Attributes:
        id:          Unique check ID (e.g. AFW001).
        status:      pass / warn / fail.
        category:    Logical group for panel rendering.
        message:     One-line summary shown in diagnostics hover.
        detail:      Extended explanation for the panel card.
        line:        1-indexed line in the source file (0 if unknown).
        column:      0-indexed column (0 if unknown).
        end_line:    End line for range highlighting (same as line if single-line).
        end_column:  End column for range highlighting.
        source_rule: Human-readable rule name for documentation links.
    """
    id: str
    status: CheckStatus
    category: CheckCategory
    message: str
    detail: str = ""
    line: int = 0
    column: int = 0
    end_line: int = 0
    end_column: int = 0
    source_rule: str = ""

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["status"] = self.status.value
        d["category"] = self.category.value
        return d


# ---------------------------------------------------------------------------
# Deterministic fix suggestion (no LLM needed)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SuggestedFix:
    """
    A deterministic, LLM-free fix suggestion.

    Generated by fuzzy-matching (difflib SequenceMatcher >= 0.80), pattern
    detection (duplicate column removal), or structural fixes.

    Attributes:
        check_id:    The CheckResult.id this fix addresses.
        description: Human-readable fix description for the lightbulb menu.
        old_text:    The exact text to replace in the source.
        new_text:    The replacement text.
        diff:        Unified diff string for preview in the panel.
        confidence:  Match confidence 0.0–1.0 (from SequenceMatcher).
        line:        Line where the fix applies.
        column:      Column where the fix applies.
    """
    check_id: str
    description: str
    old_text: str
    new_text: str
    diff: str = ""
    confidence: float = 1.0
    line: int = 0
    column: int = 0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Airflow connection fix (for live-check layer)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class AirflowConnectionFix:
    """
    Suggests creating/updating an Airflow connection.

    Rendered as a special card in the panel with a "Create Connection" button
    that calls the Airflow REST API via the engine connector.
    """
    conn_id: str
    conn_type: str
    host: str = ""
    port: int = 0
    schema: str = ""
    login: str = ""
    extra: dict[str, Any] = field(default_factory=dict)
    description: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Aggregated validation result
# ---------------------------------------------------------------------------

@dataclass
class ValidationSummary:
    """Counts by status for the status-bar display."""
    total: int = 0
    passed: int = 0
    warnings: int = 0
    failures: int = 0


@dataclass
class ValidationResult:
    """
    Complete validation output for a single file.

    This is the top-level response for the `validate` JSON-RPC method.
    """
    file_path: str
    checks: list[CheckResult] = field(default_factory=list)
    fixes: list[SuggestedFix] = field(default_factory=list)
    connection_fixes: list[AirflowConnectionFix] = field(default_factory=list)
    summary: ValidationSummary = field(default_factory=ValidationSummary)

    def compute_summary(self) -> None:
        """Recompute summary counts from the checks list."""
        self.summary = ValidationSummary(
            total=len(self.checks),
            passed=sum(1 for c in self.checks if c.status == CheckStatus.PASS),
            warnings=sum(1 for c in self.checks if c.status == CheckStatus.WARN),
            failures=sum(1 for c in self.checks if c.status == CheckStatus.FAIL),
        )

    def to_dict(self) -> dict[str, Any]:
        self.compute_summary()
        return {
            "file_path": self.file_path,
            "checks": [c.to_dict() for c in self.checks],
            "fixes": [f.to_dict() for f in self.fixes],
            "connection_fixes": [cf.to_dict() for cf in self.connection_fixes],
            "summary": asdict(self.summary),
        }


# ---------------------------------------------------------------------------
# AI remediation option (one variant: low / medium / high)
# ---------------------------------------------------------------------------

@dataclass
class CodeChange:
    """A single file change within a remediation option."""
    file_path: str
    old_content: str
    new_content: str
    description: str = ""


@dataclass
class RemediationOption:
    """
    One AI-generated fix variant.

    The engine produces up to 3 variants (low/medium/high impact).
    Each MUST pass ast.parse() + static_checks before being shown to the user.
    Failed variants are still returned with failed=True so the UI can explain why.

    Attributes:
        impact:           low / medium / high.
        title:            Short title for the fix card.
        root_cause:       Explanation of why the issue occurs.
        fix_explanation:  What this fix does and why.
        changes:          List of code changes.
        dag_code:         The complete fixed DAG code.
        diff:             Unified diff of the full file.
        failed:           True if the variant failed the static-check gate.
        failure_reason:   Why the gate rejected this variant.
        checks_after:     Validation result after applying the fix (for cascade display).
    """
    impact: FixImpact
    title: str
    root_cause: str = ""
    fix_explanation: str = ""
    changes: list[CodeChange] = field(default_factory=list)
    dag_code: str = ""
    diff: str = ""
    failed: bool = False
    failure_reason: str = ""
    checks_after: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["impact"] = self.impact.value
        return d
